"use client";

import Editor from "@monaco-editor/react";
import { useSearchParams } from "next/navigation";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Check, Clipboard, FileUp, Info, Loader2, Play, RotateCcw, Send, Sparkles, Wand2, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { examples } from "@/lib/examples";
import { supportedLanguages, maxCodeCharacters } from "@/lib/prompts";
import type { Analysis, DocumentationResult, RefactorResult, TestsResult } from "@/types/analysis";
import { getLanguageFromFilename } from "@/lib/utils";

type ChatMessage = { role:"user"|"assistant"; content:string };
const starter = examples[0];

export function CodeWorkspace(){
 const params=useSearchParams();
 const [code,setCode]=useState(starter.code); const [language,setLanguage]=useState(starter.language); const [filename,setFilename]=useState(starter.filename);
 const [analysis,setAnalysis]=useState<Analysis|null>(null); const [refactor,setRefactor]=useState<RefactorResult|null>(null); const [tests,setTests]=useState<TestsResult|null>(null); const [docs,setDocs]=useState<DocumentationResult|null>(null);
 const [loading,setLoading]=useState<string|null>(null); const [error,setError]=useState(""); const [toast,setToast]=useState(""); const [chat,setChat]=useState<ChatMessage[]>([]); const [question,setQuestion]=useState(""); const [activeLine,setActiveLine]=useState<number|null>(null); const editorRef=useRef<Parameters<NonNullable<React.ComponentProps<typeof Editor>["onMount"]>>[0]|null>(null);
 const currentExample=params.get("example");
 useEffect(()=>{if(currentExample){const ex=examples.find(x=>x.id===currentExample);if(ex){setCode(ex.code);setLanguage(ex.language);setFilename(ex.filename);setAnalysis(null);}}},[currentExample]);
 useEffect(()=>{const id=params.get("history");if(!id)return;try{const items=JSON.parse(localStorage.getItem("codeclarity-history")||"[]");const item=items.find((x: {id:string})=>x.id===id);if(item){setCode(item.code);setLanguage(item.language);setFilename(item.filename)}}catch{}},[params]);
 const flash=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(""),2200)};
 const copy=async(text:string)=>{await navigator.clipboard.writeText(text);flash("Copied to clipboard")};
 const saveHistory=()=>{const item={id:crypto.randomUUID(),filename,language,code,savedAt:new Date().toISOString()};const old=JSON.parse(localStorage.getItem("codeclarity-history")||"[]");localStorage.setItem("codeclarity-history",JSON.stringify([item,...old].slice(0,30)));flash("Saved locally")};
 const analyze=async(action:"analyze"|"refactor"|"tests"|"documentation")=>{if(!code.trim()){setError("Add some code before analyzing.");return} if(code.length>maxCodeCharacters){setError(`Code is too large. Limit is ${maxCodeCharacters.toLocaleString()} characters.`);return} setError("");setLoading(action);try{const res=await fetch("/api/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,code,language,analysis})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Request failed");if(action==="analyze")setAnalysis(data.data);if(action==="refactor")setRefactor(data.data);if(action==="tests")setTests(data.data);if(action==="documentation")setDocs(data.data);flash(action==="analyze"?"Analysis ready":`${action} generated`)}catch(e){setError(e instanceof Error?e.message:"Something went wrong")}finally{setLoading(null)}};
 const ask=async()=>{if(!question.trim())return;const q=question.trim();setQuestion("");setChat(v=>[...v,{role:"user",content:q}]);setLoading("chat");try{const res=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code,language,question:q,analysis})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Chat request failed");setChat(v=>[...v,{role:"assistant",content:data.answer}])}catch(e){setError(e instanceof Error?e.message:"Chat failed")}finally{setLoading(null)}};
 const handleUpload=(file:File)=>{if(file.size>200_000){setError("Files must be 200 KB or smaller.");return}const detected=getLanguageFromFilename(file.name);if(!supportedLanguages.some(item => item === detected)){setError("Unsupported file type.");return}const reader=new FileReader();reader.onload=()=>{setCode(String(reader.result||""));setLanguage(detected);setFilename(file.name);setAnalysis(null);setError("");};reader.readAsText(file)};
 const jumpToLine=useCallback((line:number)=>{setActiveLine(line);editorRef.current?.revealLineInCenter(line);editorRef.current?.setPosition({lineNumber:line,column:1});editorRef.current?.focus()},[]);
 const editorLanguage=useMemo(()=>language==="csharp"?"csharp":language,[language]);
 return <div className="workspace"><div className="workspace-header"><div className="workspace-title"><h1>Analyze source code</h1><p>Code is treated as untrusted text. Nothing you upload is executed.</p></div><div className="workspace-actions"><Button onClick={saveHistory}>Save</Button><Button onClick={()=>{setCode("");setAnalysis(null);setRefactor(null);setTests(null);setDocs(null)}}><X size={15}/>Clear</Button></div></div>
 <div className="workspace-grid"><section className="panel"><div className="panel-head"><div className="panel-head-left"><select className="select" value={language} onChange={e=>{setLanguage(e.target.value);setAnalysis(null)}} aria-label="Programming language">{supportedLanguages.map(x=><option key={x} value={x}>{x}</option>)}</select><input className="input" value={filename} onChange={e=>setFilename(e.target.value)} aria-label="File name"/></div><div className="panel-head-right"><label className="btn" style={{height:34}}><FileUp size={14}/>Upload<input type="file" hidden accept=".js,.ts,.jsx,.tsx,.py,.java,.cpp,.c,.cs,.go,.rs,.php,.sql" onChange={e=>{const f=e.target.files?.[0];if(f)handleUpload(f);e.currentTarget.value=""}}/></label><Button variant="ghost" onClick={()=>copy(code)} aria-label="Copy source"><Clipboard size={15}/></Button></div></div><div className="editor-wrap"><Editor height="100%" language={editorLanguage} theme="vs-dark" value={code} onChange={v=>setCode(v||"")} onMount={editor=>{editorRef.current=editor}} options={{fontSize:13,minimap:{enabled:false},padding:{top:14,bottom:14},smoothScrolling:true,wordWrap:"on",renderLineHighlight:"all",scrollBeyondLastLine:false,automaticLayout:true}} /></div><div className="editor-footer"><span className="muted small">{code.length.toLocaleString()} / {maxCodeCharacters.toLocaleString()} chars</span><Button variant="primary" disabled={!!loading} onClick={()=>analyze("analyze")}><Play size={15}/>{loading==="analyze"?"Analyzing…":"Analyze Code"}</Button></div></section>
 <section className="panel results-panel"><div className="results-tabs"><Tabs defaultValue="overview"><TabsList><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="issues">Issues</TabsTrigger><TabsTrigger value="complexity">Complexity</TabsTrigger><TabsTrigger value="lines">Lines</TabsTrigger><TabsTrigger value="refactor">Refactor</TabsTrigger><TabsTrigger value="tests">Tests</TabsTrigger><TabsTrigger value="documentation">Docs</TabsTrigger><TabsTrigger value="chat">Chat</TabsTrigger></TabsList><TabsContent value="overview"><Overview analysis={analysis} loading={loading==="analyze"} error={error}/></TabsContent><TabsContent value="issues"><Issues analysis={analysis} jump={jumpToLine}/></TabsContent><TabsContent value="complexity"><Complexity analysis={analysis}/></TabsContent><TabsContent value="lines"><Lines analysis={analysis} jump={jumpToLine}/></TabsContent><TabsContent value="refactor"><ActionResult type="refactor" result={refactor} loading={loading==="refactor"} onGenerate={()=>analyze("refactor")} onCopy={()=>refactor&&copy(refactor.code)}/></TabsContent><TabsContent value="tests"><ActionResult type="tests" result={tests} loading={loading==="tests"} onGenerate={()=>analyze("tests")} onCopy={()=>tests&&copy(tests.tests)}/></TabsContent><TabsContent value="documentation"><ActionResult type="documentation" result={docs} loading={loading==="documentation"} onGenerate={()=>analyze("documentation")} onCopy={()=>docs&&copy(docs.documentation)}/></TabsContent><TabsContent value="chat"><div className="chat"><div className="notice" style={{marginBottom:12}}><Sparkles size={13} style={{verticalAlign:"-2px",marginRight:5}}/> Chat is grounded in the current {language} source and any completed analysis.</div><div className="chat-messages">{chat.length===0?<div className="empty"><div><strong>Ask about the current code</strong><span>Try “Why is this O(n²)?” or “What happens if the input is empty?”</span></div></div>:chat.map((m,i)=><div key={i} className={`message ${m.role}`}>{m.content}</div>)}{loading==="chat"&&<div className="message assistant"><Loader2 size={14} className="spin"/> Thinking about the code…</div>}</div><div className="chat-form"><textarea className="chat-input" value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();ask()}}} placeholder="Ask a question about this code…"/><Button variant="primary" onClick={ask} disabled={loading==="chat"}><Send size={15}/></Button></div></div></TabsContent></Tabs></div></section></div>{toast&&<div className="toast">{toast}</div>}
 </div>
}

function Overview({analysis,loading,error}:{analysis:Analysis|null;loading:boolean;error:string}){if(loading)return <Loading/>;if(error)return <div className="empty"><div><strong>Could not complete analysis</strong><span>{error}</span></div></div>;if(!analysis)return <div className="empty"><div><strong>Run an analysis to populate this panel</strong><span>The overview will include summary, quality, findings and complexity.</span></div></div>;return <><div className="notice"><strong>Detected language:</strong> {analysis.language}</div><p className="summary">{analysis.summary}</p><div className="score-row"><div><div className="muted small">AI quality heuristic</div><div className="score">{analysis.qualityScore}<span className="muted" style={{fontSize:15}}>/100</span></div></div><div className="progress"><span style={{width:`${analysis.qualityScore}%`}}/></div></div><div className="metrics"><div className="metric"><div className="metric-label">Time</div><div className="metric-value">{analysis.complexity.time}</div></div><div className="metric"><div className="metric-label">Space</div><div className="metric-value">{analysis.complexity.space}</div></div></div><div className="findings">{analysis.keyFindings.map((f,i)=><div className={`finding ${f.type}`} key={i}><Check size={15}/><span>{f.text}</span></div>)}</div><p className="muted small" style={{marginTop:14}}>The score is an AI-generated heuristic, not an objective static-analysis measurement.</p></>}
function Issues({analysis,jump}:{analysis:Analysis|null;jump:(line:number)=>void}){if(!analysis)return <div className="empty"><div><strong>No issues yet</strong><span>Run an analysis first.</span></div></div>;return <div>{analysis.issues.length===0?<div className="empty"><div><strong>No issues were identified</strong><span>This does not prove the code is defect-free.</span></div></div>:analysis.issues.map((issue,i)=><div className={`issue ${issue.severity}`} key={i}><div className="issue-top"><span className="issue-title">{issue.title}</span><span className="severity">{issue.severity}</span></div>{issue.line&&<button className="line-button" onClick={()=>jump(issue.line!)}>Line {issue.line}</button>}<p>{issue.description}</p><p><strong>Why it matters:</strong> {issue.whyItMatters}</p><p><strong>Suggested fix:</strong> {issue.suggestion}</p></div>)}</div>}
function Complexity({analysis}:{analysis:Analysis|null}){if(!analysis)return <div className="empty"><div><strong>No complexity analysis</strong><span>Run an analysis first.</span></div></div>;const c=analysis.complexity;return <><div className="metrics"><div className="metric"><div className="metric-label">Time complexity</div><div className="metric-value">{c.time}</div></div><div className="metric"><div className="metric-label">Space complexity</div><div className="metric-value">{c.space}</div></div></div><p className="summary">{c.explanation}</p><div className="two-col"><div className="card"><div className="metric-label">Best case</div><p className="small">{c.bestCase||"Not confidently determined."}</p></div><div className="card"><div className="metric-label">Average case</div><p className="small">{c.averageCase||"Not confidently determined."}</p></div><div className="card"><div className="metric-label">Worst case</div><p className="small">{c.worstCase||"Not confidently determined."}</p></div><div className="card"><div className="metric-label">Confidence</div><p className="small">{c.confidence}</p></div></div></>}
function Lines({analysis,jump}:{analysis:Analysis|null;jump:(line:number)=>void}){if(!analysis)return <div className="empty"><div><strong>No line explanations</strong><span>Run an analysis first.</span></div></div>;return <div>{analysis.lineExplanations.map((line)=><div className="issue" key={line.line}><button className="line-button" onClick={()=>jump(line.line)}>Line {line.line}</button><pre className="code-block" style={{margin:"8px 0"}}>{line.code}</pre><p style={{margin:0}}>{line.explanation}</p></div>)}</div>}
function ActionResult({type,result,loading,onGenerate,onCopy}:{type:"refactor"|"tests"|"documentation";result:RefactorResult|TestsResult|DocumentationResult|null;loading:boolean;onGenerate:()=>void;onCopy:()=>void}){if(loading)return <Loading/>;if(!result)return <div className="empty"><div><strong>Nothing generated yet</strong><span>Generate {type} for the current source.</span><div style={{marginTop:14}}><Button variant="primary" onClick={onGenerate}><Wand2 size={15}/>Generate</Button></div></div></div>;if(type==="refactor"){const r=result as RefactorResult;return <><div className="workspace-actions" style={{marginBottom:12}}><Button variant="primary" onClick={onCopy}><Clipboard size={14}/>Copy Code</Button></div><h3>Suggested refactor</h3><pre className="code-block">{r.code}</pre><h3>What changed</h3><ul>{r.changes.map(x=><li className="small" key={x}>{x}</li>)}</ul><p className="summary">{r.rationale}</p></>}if(type==="tests"){const r=result as TestsResult;return <><div className="notice"><strong>{r.framework}</strong> · {r.strategy}</div><div className="workspace-actions" style={{margin:"12px 0"}}><Button onClick={onCopy}><Clipboard size={14}/>Copy Tests</Button></div><pre className="code-block">{r.tests}</pre><h3>Edge cases</h3><ul>{r.edgeCases.map(x=><li className="small" key={x}>{x}</li>)}</ul><p className="summary">{r.expectedBehavior}</p></>}const r=result as DocumentationResult;return <><div className="workspace-actions" style={{marginBottom:12}}><Button onClick={onCopy}><Clipboard size={14}/>Copy Documentation</Button></div><p className="summary">{r.overview}</p><pre className="code-block" style={{whiteSpace:"pre-wrap"}}>{r.documentation}</pre>{r.usageExample&&<><h3>Usage example</h3><pre className="code-block">{r.usageExample}</pre></>}</>}
function Loading(){return <div className="empty"><div><div className="loading-steps"><div className="loading-step"><span className="dot done"/>Reading source</div><div className="loading-step"><span className="dot done"/>Detecting patterns</div><div className="loading-step"><span className="dot active"/>Checking potential issues</div><div className="loading-step"><span className="dot"/>Preparing recommendations</div></div></div></div>}
